# Generated by Django 3.2.16 on 2024-04-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240429_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id_pole',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id_pole',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id_pole',
        ),
    ]
